// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmlgtgkzmhmiaotpzdyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtbGd0Z2t6bWhtaWFvdHB6ZHlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMjE4MTQsImV4cCI6MjA3MjU5NzgxNH0.BEMUfO11mMa9lzCUjmD5V7ypcfwQhB7oMyeQI2lvXEw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});